baseURL = "https://jenny.chenglinks.com/"
languageCode = "en-us"
title = "Fiona Wheats' Gleanings"
sectionPagesMenu = "main"
[menu]

  [[menu.main]]
    identifier = "book-reviews"
    name = "Book Reviews"
    url = "/book-reviews/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 1